---
apiVersion: v1
kind: Service
metadata:
  name: k8scaddy
  labels:
    app: k8scaddy
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: caddypod
