apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: caddyvsvc
spec:
  gateways:
  - caddygw
  hosts:
  - "*"
  http:
  - match:
    - uri:
        exact: /
    route:
      - destination:
          host: k8scaddy
          port:
            number: 80
