---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: caddygw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "k8scaddy.arena.networkart.com"
    - "k8scaddyint.arena.networkart.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "k8scaddy.arena.networkart.com"
    - "k8scaddyint.arena.networkart.com"
    tls:
      mode: PASSTHROUGH
